// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6N0ikpzaT02m3OdS_-dmsPkA9wLnDTo0',
    appId: '1:359793624671:android:aeb6fe0e08ffc8dcf4fdea',
    messagingSenderId: '359793624671',
    projectId: 'aura-smart-home-00',
    databaseURL: 'https://aura-smart-home-00-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aura-smart-home-00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8oj7hO6E8JJfZTCTk7ovrLNODD4Bf-eo',
    appId: '1:359793624671:ios:1519e6ec27838bb3f4fdea',
    messagingSenderId: '359793624671',
    projectId: 'aura-smart-home-00',
    databaseURL: 'https://aura-smart-home-00-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aura-smart-home-00.firebasestorage.app',
    iosClientId: '359793624671-det3gks456sl3bersd1u9k8m4of9dtfh.apps.googleusercontent.com',
    iosBundleId: 'com.aura.auraApp',
  );
}
